spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation
    username: admin
    password: 411311pwy!
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
